spring:
  application:
    name: zb-financial

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    #use-new-id-generator-mapping? ??? ???? ???? ?
    show-sql: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:finance
    username: sa
    password:
  data:
    redis:
      port: 6379
      host: localhost
pwd : hello